text2image --output_word_boxes \
--fontconfig_tmpdir=/tmp/font_tmp.wcKJAlQRQE \
--fonts_dir=fonts \
--strip_unrenderable_words \
--leading=32 \
--xsize=3600 \
--char_spacing=0.0 \
--exposure=0 \
--outputbase=/tmp/mya-2021-09-30.Whl/mya.Pyidaungsu.exp0 \
--max_pages=10 \
--font=Pyidaungsu \
--ptsize 12 \
--text=./shn_train_break.txt